# Example for using customized model and data loader.
# Model and data loader defined in custom_model_data.py
# python abcrown.py --config exp_configs/tutorial_examples/custom_cifar_data_example.yaml
model:
  # Model is defined as simple_conv_model() in custom_model_data.py. The function simple_conv_model() will be called with arguments in_channel=3, out_dim=10.
  # name: Customized("custom_model_data", "simple_conv_model", in_channel=3, out_dim=10)
  # name: Customized("custom_model_data", "googlenet")
  name : custom
  # name : trained_modelgooglenet_mnist
  # Path to model checkpoint.
  path: /home/Cyz0327/sample_data/trained_modelgooglenet_mnist.pth
data:
  # Use the cifar10() loader in "custom_model_data.py".
  dataset: Customized("custom_model_data", "image_folder")
  data_path: /home/Cyz0327/sample_data/mnist
  num_outputs: 10
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 100
